extends SceneTree

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var arena := load("res://scenes/arena.tscn").instantiate() as Node3D
	root.add_child(arena)
	current_scene = arena
	arena.set_physics_process(false)
	var player: CharacterBody3D = arena.get("player")
	player.set_physics_process(false)
	for kind in [0, 1, 2, 4]:
		assert(player.call("apply_upgrade", kind, 1.0))
	var slots: Array = player.get("buff_slots").duplicate()
	var stacks: Dictionary = player.get("buff_stacks").duplicate()
	var crystal_effects: Dictionary = player.get("tome_bonuses").duplicate()
	var rewards := preload("res://scripts/shrine_rewards.gd")
	for kind in rewards.CATALOG:
		assert(player.call("apply_character_buff", kind, rewards.roll(kind, 0)))
	assert(player.get("buff_slots") == slots and player.get("buff_stacks") == stacks)
	assert(player.get("tome_bonuses") == crystal_effects)
	var statue: StaticBody3D = get_nodes_in_group("buff_statues")[0]
	player.global_position = statue.global_position + Vector3(0, 0.1, 2)
	assert(statue.call("offers", player).size() == 3)
	assert(statue.call("claim", player, 0).ok)
	assert(player.get("buff_slots") == slots)
	player.set("shield", 5.0)
	player.set("health", 100)
	player.call("refresh_shield_bar")
	var blue: Node3D = player.get("shield_bar")
	assert(blue.visible and blue.position.y > player.get("health_bar").position.y)
	player.set("damage_grace_left", 0.0)
	player.call("take_damage", 3)
	assert(player.get("health") == 100 and player.get("shield") == 2)
	player.set("damage_grace_left", 0.0)
	player.call("take_damage", 4)
	assert(player.get("health") == 98 and player.get("shield") == 0)
	player.call("apply_character_buff", 31, 1.0)
	player.set("coyote_left", 0.0)
	player.set("jumps_used", 1)
	var maximum: int = player.call("max_jumps")
	for i in range(maximum - 1):
		assert(player.call("try_jump"))
	assert(not player.call("try_jump"))
	player.set("coyote_left", 0.12)
	assert(player.call("try_jump") and player.get("jumps_used") == 1)
	var visual: Node3D = player.get("visual")
	visual.call("animate", 0.1, 0.0, false, false, 5.0)
	visual.call("_process", 1.0)
	var model: Node3D = visual.get("model")
	assert(model.global_basis.y.dot(-visual.global_basis.z) > 0.05)
	var menu := arena.get_node("UpgradeMenu")
	player.set("coins", 10000.0)
	menu.call("queue_level", 2)
	for i in range(3):
		var price: int = menu.call("action_price")
		var before: float = player.get("coins")
		menu.call("toggle_ban")
		assert(player.get("coins") == before)
		menu.call("choose", 0)
		assert(player.get("coins") == before - price)
	assert(menu.get("banned").size() == 3)
	menu.call("toggle_ban")
	assert(not menu.get("ban_mode"))
	assert(menu.call("action_price") == 225)
	for expected in [225, 325, 425, 525, 525]:
		assert(menu.call("action_price") == expected)
		var before: float = player.get("coins")
		menu.call("reroll_choices")
		assert(player.get("coins") == before - expected)
	var uses: int = menu.get("action_uses")
	player.set("coins", 0.0)
	menu.call("reroll_choices")
	menu.call("skip_level")
	assert(menu.get("choosing") and menu.get("action_uses") == uses)
	player.set("coins", 525.0)
	menu.call("skip_level")
	assert(player.get("coins") == 0.0 and not menu.get("choosing"))
	print("Direct buffs, shield-first damage, air jumps, shared prices and three bans: PASS")
	quit()
