extends SceneTree
const Rewards = preload("res://scripts/shrine_rewards.gd")

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var arena := load("res://scenes/arena.tscn").instantiate() as Node3D
	root.add_child(arena)
	current_scene = arena
	arena.set_physics_process(false)
	var player: CharacterBody3D = arena.get("player")
	player.set_physics_process(false)
	for level in [1, 10, 11, 20, 21, 30, 31, 40, 41, 100]:
		player.set("level", level)
		assert(player.call("xp_required") == (int((level - 1) / 10) + 1) * 100)
	player.set("level", 10)
	player.set("xp", 90)
	player.call("collect_xp", 260)
	assert(player.get("level") == 12 and player.get("xp") == 50)
	paused = false
	var upgrades := arena.get_node("UpgradeMenu")
	upgrades.set("choosing", false)
	upgrades.get("overlay").hide()
	var statues := get_nodes_in_group("buff_statues")
	assert(statues.size() == 15)
	var statue: StaticBody3D = statues[0]
	player.global_position = statue.global_position + Vector3(0, 0.1, 2)
	player.set("coins", 0.0)
	var offered: Array[Dictionary] = statue.call("offers", player)
	assert(offered.size() == 3)
	var kinds := {}
	for reward in offered:
		assert(reward.kind in Rewards.CATALOG and reward.rarity == 0)
		kinds[reward.kind] = true
	assert(kinds.size() == 3)
	assert(statue.call("offers", player) == offered)
	var shops := arena.get_node("StatueShops")
	shops.call("open_choices", statue)
	assert(paused and shops.get("choice_menu").visible)
	shops.call("close_choices")
	assert(not paused and not statue.get("purchased"))
	shops.call("open_choices", statue)
	shops.call("choose", 0)
	assert(not paused and statue.get("purchased"))
	assert(player.get("coins") == 0.0)
	assert(not statue.call("claim", player, 1).ok)
	assert(Rewards.roll(1, 0) == 1.0)
	assert(Rewards.roll(7, 0) == 20.0)
	assert(Rewards.roll(8, 0) == 5.0)
	for i in range(30):
		var damage := Rewards.roll(15, 0)
		assert(damage >= 10 and damage <= 12)
	# Verifique as novas camadas sem depender do buff aleatório escolhido acima.
	player.set("tome_bonuses", {})
	player.set("character_buffs", {})
	player.set("buff_slots", [])
	player.set("buff_stacks", {})
	player.call("apply_character_buff", 30, 10.0)
	assert(is_equal_approx(pow(player.call("effective_jump_speed") / player.get("jump_speed"), 2), 1.1))
	player.call("apply_character_buff", 28, 10.0)
	player.set("xp", 0)
	player.call("collect_xp", 50, true)
	assert(player.get("xp") == 55)
	var hud := arena.get_node("GameHUD")
	hud.call("_process", 0.01)
	assert(hud.get("xp_bar").max_value == 200)
	player.get("buff_slots").clear()
	player.call("apply_character_buff", 27, 10.0)
	player.call("apply_character_buff", 29, 10.0)
	player.call("apply_character_buff", 20, 6.0)
	var target := Node3D.new()
	target.set_script(preload("res://tests/reward_target.gd"))
	target.add_to_group("elites")
	arena.add_child(target)
	player.get("weapons")[10].crit_chance = 100.0
	player.set("health", 50)
	player.call("hit_enemy", target, 100, 0.0, 10)
	assert(target.get("health") == 9758)
	assert(player.get("health") == 64)
	player.get("buff_slots").clear()
	player.call("apply_character_buff", 8, 5.0)
	player.call("apply_character_buff", 7, 20.0)
	assert(player.get("shield") == 5.0)
	player.call("update_survival", 3.0)
	assert(player.get("health") == 65)
	player.set("damage_grace_left", 0.0)
	player.call("take_damage", 4)
	assert(player.get("health") == 65 and player.get("shield") == 1.0)
	print("Shrine/progression: PASS (free choice, stable offers, all XP bands, jump, power-up)")
	quit()
