extends SceneTree

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var arena := load("res://scenes/arena.tscn").instantiate() as Node3D
	root.add_child(arena)
	current_scene = arena
	var player: CharacterBody3D = arena.get("player")
	player.set_physics_process(false)
	for kind in preload("res://scripts/tomes.gd").catalog():
		player.get("buff_slots").clear()
		assert(player.call("apply_upgrade", kind, 10.0, 4))
	assert(player.get("max_health") >= 110)
	assert(player.call("effective_weapon_damage", 10) >= 110)
	assert(player.call("weapon_radius", 11, 3.0) > 3.0)
	assert(player.call("collection_radius") > 2.2)
	assert(player.call("effect_duration", 3.0) > 3.0)
	assert(player.get("chaos_results").size() == 1)
	player.get("buff_slots").clear()
	for kind in [6, 7, 8, 9]:
		assert(player.call("apply_upgrade", kind, 1.0))
	assert(not player.call("apply_upgrade", 15, 1.0))
	assert(player.call("eligible_buffs", preload("res://scripts/tomes.gd").catalog()).size() == 4)
	player.set("health", 50)
	player.set("shield", 0.0)
	player.call("update_survival", 5.0)
	assert(player.get("health") > 50)
	assert(player.get("shield") > 0.0)
	var before: int = player.get("health")
	player.call("take_damage", 5, null, 1.0)
	assert(player.get("health") == before, "Escudo absorve o dano")
	player.set("damage_grace_left", 0.0)
	player.set("shield", 0.0)
	player.call("take_damage", 10, null, 0.0)
	assert(player.get("health") == before, "Evasão evita dano")
	player.set("damage_grace_left", 0.0)
	player.call("take_damage", 100, null, 1.0)
	assert(before - player.get("health") < 100, "Armadura reduz dano")
	player.set("health", 50)
	player.set("dead", false)
	var enemy := CharacterBody3D.new()
	enemy.set_script(load("res://scripts/enemy.gd"))
	enemy.set("max_health", 500)
	enemy.position = player.position + Vector3(1, 0, 0)
	arena.add_child(enemy)
	player.call("hit_enemy", enemy, 100, 0.0)
	assert(enemy.get("health") == 300, "Crítico dobra o dano")
	assert(player.get("health") > 50, "Roubo de vida cura")
	assert(enemy.get("knockback").length() > 0.0)
	player.set("damage_grace_left", 0.0)
	player.call("take_damage", 20, enemy, 1.0)
	assert(enemy.get("health") < 300, "Espinhos refletem dano")
	player.call("collect_bonus")
	assert(player.get("coins") > 1.0)
	player.call("spawn_arrow", player.position + Vector3.UP, Vector3.FORWARD)
	var arrow: Node3D = get_nodes_in_group("arrows").back()
	assert(arrow.get("speed") > 32.0 and arrow.get("lifetime") > 3.0 and arrow.get("hit_radius") > 0.04)
	var menu := arena.get_node("UpgradeMenu")
	menu.call("queue_level", 2)
	for kind in menu.get("offered"):
		assert(kind in [6, 7, 8, 9, 10, 11, 12])
	menu.call("choose", 0)
	await physics_frame
	print("Tomes: PASS")
	quit(0)
